Done ENUM
Medmex9/OOP3 pull request #2
Opened 2023-01-29 15:40 UTC by Medmex9

2023-02-05 11:20 UTC, Medmex9 commented
Done Exceptions3

2023-02-08 20:33 UTC, alekseykoshelev requested changes

2023-02-08 20:33 UTC, alekseykoshelev commented on src/Transport/Auto.java
> +    private List<Mechanics<?>> mechanics; // Создан список механиков с помощью List в классе Transport.
А как добавить механика в этот список?

2023-02-08 20:33 UTC, alekseykoshelev commented on src/Transport/ServiceStation.java
> +    public Queue <Auto<?>> queue = new LinkedList<>();
Лучше private

2023-02-08 20:33 UTC, alekseykoshelev commented on src/Transport/ServiceStation.java
> +        else queue.add(auto);
Можно тогда для однообразия и у else добавить скобки)

2023-02-21 19:25 UTC, alekseykoshelev commented on src/Transport/Truck.java
> +        return super.equals(o);
Такие методы, у которых код идентичен коду родителя, можно не переопределять

2023-02-21 19:27 UTC, alekseykoshelev commented on src/Transport/Car.java
> +        return super.hashCode();
Нужно, чтобы в этом хешкоде участвовало поле `typeOfBody`. Вот так `Objects.hash(typeOfBody, super.hashCode());`

2023-02-23 04:28 UTC, closed without merging